title: Taeblog
author: Tae Hyoung Jo
email: taehyoung.jo@yale.edu
description: > # this means to ignore newlines until "baseurl:"
  This is the online home of the musings and projects of THJ

linkedin_username: taehyoungjo
github_username:  taehyoungjo
rss: rss

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
